services:
    zebrands_web:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        # command: python ./src/manage.py runserver 0.0.0.0:8000 --settings=config.settings.local
        entrypoint: /docker-entrypoint.sh
        volumes:
            - ./src:/www/src
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            zebrands_db:
                condition: service_healthy
    zebrands_db:
        image: "postgres:14-alpine"
        restart: unless-stopped
        env_file:
            - ./.env
        ports:
            - "5436:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            retries: 5
            timeout: 5s
