# Generated by Django 5.0 on 2024-07-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='ProductChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_channels', to='products.channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_channels', to='products.product')),
            ],
            options={
                'verbose_name': 'ProductChannel',
                'verbose_name_plural': 'Product Channels',
                'unique_together': {('product', 'channel')},
            },
        ),
    ]
